Repository radixdlt/sargon, pull requests merged in 2024-06, with the labels that each got.

#160 Truncate Decimal192 fractional part when it has more than 18 decimals
  Cargo.lock
  Cargo.toml
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt
  src/core/types/decimal192.rs
  src/core/types/decimal192_uniffi_fn.rs
Labels: Coverage OK ☂️ ✅, Rust 🦀, Kotlin 🤖

#163 Implement RadixConnectSessionStorage for kotlin
  jvm/gradle/libs.versions.toml
  jvm/sargon-android/build.gradle.kts
  jvm/sargon-android/src/androidTest/kotlin/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorageTest.kt
  jvm/sargon-android/src/androidTest/kotlin/com/radixdlt/sargon/os/storage/EncryptionHelperWithSpecKeyTest.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Result.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorage.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/EncryptedPreferencesStorage.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/EncryptionHelper.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/KeySpec.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/ResultTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorageTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/EncryptedPreferencesStorageTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/EncryptionHelperWithEncryptionKeyTest.kt
Labels: Kotlin 🤖

#165 Optional request body for `GET` methods
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/antenna/SargonNetworkAntenna.kt
Labels: Kotlin 🤖

#162 [ABW-3230] Update Wallet Interaction models
  Cargo.lock
  Cargo.toml
  apple/Sources/Sargon/Extensions/Methods/RadixConnect/WalletInteraction/DappToWalletInteractionUnvalidated+Wrap+Functions.swift
  apple/Sources/Sargon/Extensions/Methods/RadixConnect/WalletInteraction/UnvalidatedTransactionManifest+Wrap+Functions.swift
  apple/Sources/Sargon/Extensions/Methods/RadixConnect/WalletInteraction/WalletToDappInteractionResponse+Wrap+Functions.swift
  apple/Sources/Sargon/Extensions/Methods/RadixConnect/WalletInteractionVersion+Wrap+Functions.swift
  apple/Sources/Sargon/Extensions/Methods/RadixConnect/WalletInteractionWalletAccount+Wrap+Functions.swift
  apple/Sources/Sargon/Extensions/SampleValues/RadixConnect/WalletInteraction/DappToWalletInteractionUnvalidated+SampleValues.swift
  apple/Sources/Sargon/Extensions/SampleValues/RadixConnect/WalletInteraction/UnvalidatedTransactionManifest+SampleValues.swift
  apple/Sources/Sargon/Extensions/SampleValues/RadixConnect/WalletInteraction/WalletToDappInteractionResponse+SampleValues.swift
  apple/Sources/Sargon/Extensions/SampleValues/RadixConnect/WalletInteractionWalletAccount+SampleValues.swift
  apple/Sources/Sargon/Extensions/Swiftified/RadixConnect/WalletInteraction/DappToWalletInteractionUnvalidated+Swiftified.swift
  apple/Sources/Sargon/Extensions/Swiftified/RadixConnect/WalletInteraction/UnvalidatedTransactionManifest+Swiftified.swift
  apple/Sources/Sargon/Extensions/Swiftified/RadixConnect/WalletInteraction/WalletToDappInteractionResponse+Swiftified.swift
  apple/Sources/Sargon/Extensions/Swiftified/RadixConnect/WalletInteractionWalletAccount+Swiftified.swift
  apple/Tests/TestCases/RadixConnect/WalletInteraction/DappToWalletInteractionUnvalidatedTests.swift
  apple/Tests/TestCases/RadixConnect/WalletInteraction/UnvalidatedTransactionManifestTests.swift
  apple/Tests/TestCases/RadixConnect/WalletInteraction/WalletToDappInteractionResponseTests.swift
  apple/Tests/TestCases/RadixConnect/WalletInteractionWalletAccountTests.swift
  fixtures/vector/wallet_interactions_dapp_to_wallet.json
  fixtures/vector/wallet_interactions_wallet_to_dapp.json
  src/radix_connect/interaction_id.rs
  src/radix_connect/interaction_version.rs
  src/radix_connect/interaction_version_uniffi_fn.rs
  src/radix_connect/mobile/deep_link_parsing/dapp_request.rs
  src/radix_connect/mod.rs
  src/radix_connect/wallet_account.rs
  src/radix_connect/wallet_account_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/auth_challenge_nonce.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/dapp_to_wallet_interaction_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/auth/login_with_challenge.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/entity/accounts.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/transaction/mod.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/transaction/transaction.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/transaction/unvalidated_transaction_manifest.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/transaction/unvalidated_transaction_manifest_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/mod.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/mod.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/response_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/account/accounts.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/auth/auth_login_with_challenge.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/transaction/transaction.rs
  src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/blobs/blob.rs
  src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/blobs/blobs.rs
  src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/blobs/blobs_secret_magic.rs
  src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest.rs
  src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest_uniffi_fn.rs
  tests/vectors/main.rs
Labels: Swift 🍏, Rust 🦀, UniFFI 🦄

#167 Redo PR #164 since some methods of `RadixConnectMobileLinkRequest` were deleted
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/RadixConnectMobileLinkRequest.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/RadixConnectMobileSessionRequest.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/samples/RadixConnectMobileLinkRequestSample.kt
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/samples/RadixConnectMobileSessionRequestSample.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/NotarizedTransactionTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/RadixConnectMobileLinkRequestTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/RadixConnectMobileSessionRequestTest.kt
  jvm/sargon-android/src/test/java/com/radixdlt/sargon/TransactionIntentTest.kt
  src/radix_connect/mobile/session_dapp_request.rs
Labels: Kotlin 🤖, UniFFI 🦄

#166 Add dapp origin type
  Cargo.lock
  Cargo.toml
  fixtures/vector/wallet_interactions_dapp_to_wallet.json
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/dapp_metadata/interaction_metadata.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/dapp_metadata/interaction_metadata_unvalidated.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/dapp_metadata/mod.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/dapp_metadata/origin.rs
  tests/vectors/main.rs
Labels: Coverage OK ☂️ ✅

#169 Pass serde message information to `FailedToDeserializeJSONToValue`
  Cargo.lock
  Cargo.toml
  jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/MnemonicWithPassphrase.kt
  src/core/error/common_error.rs
  src/core/error/common_error_map.rs
  src/core/error/mod.rs
  src/profile/v100/json_data_convertible.rs
  src/profile/v100/profile.rs
  src/profile/v100/profile_uniffi_fn.rs
  src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_uniffi_fn.rs
  src/wallet/secure_storage/wallet_client_storage.rs
Labels: Rust 🦀, Kotlin 🤖

#171 Truncate display names with longer than 30 chars
  Cargo.lock
  Cargo.toml
  apple/Tests/TestCases/Prelude/DisplayNameTests.swift
  src/core/error/common_error.rs
  src/core/error/common_error_map.rs
  src/core/utils/string_utils.rs
  src/profile/v100/entity/display_name.rs
Labels: Rust 🦀

#168 [ABW-3454] iOS - Display proper error messages for Sargon errors
  Cargo.lock
  Cargo.toml
  apple/Sources/Sargon/Extensions/Swiftified/Prelude/SargonError+Swiftified.swift
  apple/Tests/TestCases/Prelude/SargonErrorTests.swift
  src/core/error/common_error.rs
Labels: Swift 🍏

#173 Add some extra metadata fields when creating token
  Cargo.lock
  Cargo.toml
  apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
  fixtures/transaction/create_3_nft_collections.rtm
  src/wrapped_radix_engine_toolkit/high_level/manifest_building/manifests_create_tokens.rs
  src/wrapped_radix_engine_toolkit/high_level/token_definition_metadata.rs
Labels: Rust 🦀
